# These are supported funding model platforms

# Well,You maybe want to give me a cup of milktea?

patreon: CHonesetDoPa
custom: ['https://me.nekoc.cc/assets/sponsor/app1.png','https://me.nekoc.cc/assets/sponsor/app2.png','https://me.nekoc.cc/assets/sponsor/app3.png']
