# These are supported funding model platforms

# Well,You maybe want to give me a cup of milktea?

patreon: CHonesetDoPa
custom: ['image/sponsor/app1.png','image/sponsor/app2.png','image/sponsor/app3.png']
